### ISSUE TITLE
Class not registered exception when attempting to use library

### ISSUE THREAD

**Issue by Strahan201** [falahati/WindowsFirewallHelper#65]
Hi!

I found this library and was happy to see how easy it would make adding a rule for my app.  I did:

`if (FirewallManager.Instance.Rules.Any(x => x.Name.Matches("GameManager"))) return;
`

When I run it, I'm getting:

```
System.Runtime.InteropServices.COMException
  HResult=0x80040154
  Message=Retrieving the COM class factory for component with CLSID {9C27C8DA-189B-4DDE-89F7-8B39A316782C} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
  Source=mscorlib
  StackTrace:
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at WindowsFirewallHelper.COMTypeResolver.CreateInstance[T]() in C:\Users\s_fal\Documents\Personal\Open-Source Projects\WindowsFirewallHelper\WindowsFirewallHelper\COMTypeResolver.cs:line 71
```

Any idea what's going on?  Thanks!

**Comment by kamronbatman** [comment]
See my answer here: https://github.com/falahati/WindowsFirewallHelper/issues/68#issuecomment-2676682571

**Comment by falahati** [comment]
This means that the application is running on another CPU instruction than your OS.

For example, you might be on Any CPU mode, with Prefer 32bit enabled, but running the code on an x64 OS.

Either change the compilation mode to target a specific architecture, or disable the Prefer32Bit option.

The error message simply states that no such COM class is registered.
